# Generated by Django 3.2.20 on 2023-09-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Roll', models.IntegerField()),
                ('City', models.CharField(max_length=50)),
            ],
        ),
    ]
