# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-07-13 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.CharField(max_length=1000)),
            ],
        ),
    ]
