# Generated by Django 3.2.20 on 2023-08-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_feedbackform'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='BMT', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='feedback',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
