# Generated by Django 3.2.20 on 2023-08-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20230817_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackform',
            name='id',
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='rollno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
