# Generated by Django 5.0.1 on 2024-04-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empno',
            field=models.IntegerField(),
        ),
    ]
